### PR TITLE
IRONFIST Catherine speech in Armaggeddon's Blade campaign

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
⚠️ This PR requires to be proofread by a German speaker ⚠️

Hi @misiokles & @heroesiiifan,

This PR translates the second prolog of the _Armaggeddon's Blade_ campaign, that is to say the fist _Catherine IRONFIST_'s speech. I can redo any sentence independantly. The result is very good in French.

# How to do the same
1. Concatenate all the [Catherine IRONFIST speeches](https://github.com/user-attachments/files/17345453/Catherine.IRONFIST.g1a.zip) or [search a free German podcast](https://www.youtube.com/results?search_query=podcast+Geschichte&sp=EgIwAQ%253D%253D) without music like [this](https://www.youtube.com/watch?v=NpmYCCU5UuY#t=140m00)
2. Go to [XTTS](https://huggingface.co/spaces/coqui/xtts)
3. Select the _German_ language
4. Put the _Catherine IRONFIST_ speeches as _Reference audio_
5. Paste one sentence from `german-translation\content\config\vcmi-german\campaigns.json`
6. Check the ckeckboxes _Cleanup Reference Voice_, _Do not use language auto-detect_ & _Agree_
7. Start the generation
8. Restart the generation to try to get a better result
9. Concatenate the generations with _Audacity_ adding silences between the sentences
10. Export the audio as `.ogg`
11. Put the file in `german-translation\content\sounds` with the right name like `ABvoAB1.ogg`
12. Start _VCMI_
13. Reach the second scenario of the _Armaggeddon's Blade_ campaign by using [cheat codes](https://vcmi.eu/players/Cheat_Codes/)

PS: I don't speak German

### CODE REVIEW

**Comment by Fabrice-TIERCELIN** [comment]
Are you a German speaker, @misiokles? It needs a proofread.

**Comment by heroesiiifan** [comment]
Hi @Fabrice-TIERCELIN 

Also seen it and also tested it by myself.

Is there a way to avoid 200 char limit? Multiple sentence at once gives better results I think. But it's not possible due limit.

**Comment by Fabrice-TIERCELIN** [comment]
Yes, [my space](https://huggingface.co/spaces/Fabrice-TIERCELIN/Multi-language_Text-to-Speech) allows up to 50,000 characters but it's slower and I don't know if it handles such a huge task. I haven't noticed better result with multiple sentences. I even saw the opposite.

Do you approve the PR?

**Comment by heroesiiifan** [comment]
> Do you approve the PR?

Have replaced it by my version, because it sounds a little bit more natural (maybe better fitting reference audio). Already translated it yesterday. :)

Thanks a lot for this approach.

Btw.: If you want to improve french translation: You can also add a chronicles translation. Because it's supported since 1.6:
https://github.com/vcmi-mods/german-translation/tree/vcmi-1.6/mods/german-translation-chronicles (also a huge potential for extra voices - if there aren't official french voices).

**Comment by Fabrice-TIERCELIN** [comment]
OK, @misiokles, can you please set `vcmi-1.6` as the default branch?

**Comment by misiokles** [comment]
I don't have rights to do this. I guess @heroesiiifan has.

**Comment by heroesiiifan** [comment]
No sadly not. :(

I've this permission for all translation repos except german and https://github.com/vcmi-mods/mega-pack-rus

@IvanSavenko Can you give me the rights to set default branches for both of them as well? If you also cannot do this: Who have the permissions?

**Comment by IvanSavenko** [comment]
@heroesiiifan 
german - done
megapack - sent invite

**Comment by heroesiiifan** [comment]
Thanks

**Comment by Fabrice-TIERCELIN** [comment]
@kdmcser, you can use the tutorial _How to do the same_ on the [campaigns](https://github.com/vcmi-mods/chinese-translation/blob/vcmi-1.4/chinese-translation/content/config/vcmi-chinese/campaigns.json)

**Comment by heroesiiifan** [comment]
For splitting background music and voice https://vocalremover.org/ is good. Worked for me for Chronicles 5 + 6 Intro. Merged afterwards translated AI voice + background music.

**Comment by Fabrice-TIERCELIN** [comment]
OK, @heroesiiifan, you can store the mute musics in the [empty-translation](https://github.com/vcmi-mods/empty-translation/tree/main/empty-translation/content) project, so that it will help all the translators

**Comment by heroesiiifan** [comment]
Hi @altiereslima
Maybe this topic is also interesting for you. As far as I know there aren't portuguese voices for Heroes 3?!

And maybe also for czech @GeorgeK1ng

Added all the missing german voices for armageddons blade and the chronicles with this help. The results are between ok to really good. But I don't know how it performs on chinese, portuguese or czech.

@Fabrice-TIERCELIN In the end I've runned the huggingface space as docker on my local pc with gpu. The creation was in my case much faster and because of that it was easier to create alternatives.

**Comment by GeorgeK1ng** [comment]
@heroesiiifan This looks really cool, Czech voice was never included in Heroes 3. I want to try this method soon to see results! It would be awesome to fully localize game with AI help!

**Comment by Fabrice-TIERCELIN** [comment]
If you have an _NVidia_ graphic card, you can also install [Pinokio](https://pinokio.computer/) and install _XTTS_ inside it. It's easy and fast.

**Comment by Fabrice-TIERCELIN** [comment]
@heroesiiifan, for the [_Unheilige Allianz_ campaign epilog](https://github.com/vcmi-mods/german-translation/blob/vcmi-1.6/content/config/vcmi-german/campaigns.json#L96C41-L96C348), I have noticed that, in the English version, _Yog_ says _"we decided to separate as well"_ at the exact moment where they separate on the video too. I think that it would be great to do the same on the translations. I will try to synchronize it in the French translation.

PS: I have gathered information about dubbing in the [empty translation](https://github.com/vcmi-mods/empty-translation/blob/main/README.md#dubbing). I plan to move it in the [VCMI documentation](https://github.com/vcmi/vcmi/blob/develop/docs/translators/Translations.md) in my further PR.

**Pull request merged**
