### PR TITLE
translation optimized

### PR DESCRIPTION
**Pull request by Laserlicht**
small optimized strings.

Can you set branch vcmi-1.2 as default after merging?

### CODE REVIEW

**Comment by Fabrice-TIERCELIN** [comment]
Hi @heroesiiifan,

I'm a French native speaker. It seems that there is no global French translation on VCMI. I'm ready to code it. Would it be possible that you create for me a repository filled in English that I can then translate?

**Comment by Laserlicht** [comment]
Hi @Fabrice-TIERCELIN 

For French there is an official translation. Check out GOG, you can download the game in French. It works fine (just tested).

But you would have to translate these files additionally if you want to have the remaining texts in VCMI French:

With simple text editor (for example [Notepad++](https://notepad-plus-plus.org/downloads/))
https://github.com/vcmi/vcmi/blob/develop/Mods/vcmi/config/vcmi/english.json

In this files replace `en_US` with `fr_FR` in the head and open & edit with [Qt Linguist](https://github.com/lelegard/qtlinguist-installers/releases/tag/v5.12.0)
https://github.com/vcmi/vcmi/blob/develop/launcher/translation/english.ts
https://github.com/vcmi/vcmi/blob/develop/mapeditor/translation/english.ts

If you are ready with these files you can make a pull request to the main repository of [vcmi](https://github.com/vcmi/vcmi) with the french files.

If you want to create translations for mods, I think @heroesiiifan can assist you there with creation of english "translation" that can be translated to french.

**Comment by Fabrice-TIERCELIN** [comment]
OK @Laserlicht so I'm ready to translate HOMM3 in Spanish 😀 Just create me the repository filled with the English version and I will translate it.

**Comment by heroesiiifan** [comment]
@Fabrice-TIERCELIN There was also a inofficial spanish translation. I've converted it to a vcmi mod. Only missing thing are the AB and SOD-Maps. If you wish, you can translate it. Feel free.
Here is the file with the existing and missing map-translation: [missing.json.zip](https://github.com/vcmi-mods/german-translation/files/11900477/missing.json.zip)

@misiokles Can you create a repository named "spanish-translation" with these files in the attachment?

**Comment by misiokles** [comment]
Done!

**Comment by Fabrice-TIERCELIN** [comment]
Hi,

How can I test a translation locally?

**Comment by misiokles** [comment]
You must download translation mod from launcher, then in launcher change language settings.
image

**Pull request merged**
